### ISSUE TITLE
`make astyle` doesn't work on macOS

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Arduino-Boards#10]
The regex used in `build-tools/run-astyle` works for GNU grep (i.e. Linux) but not BSD grep (i.e. macOS). The result is that running `make astyle` on a Mac doesn't format any `*.cpp` or `*.h` files.

**Comment by obra** [comment]
Thanks. we should also probably check in a build of astyle3 for macOS. Version 2 makes actively different formatting choices.

**Comment by gedankenexperimenter** [comment]
I'm a wee bit embarrassed that it took me so long to figure out why it hadn't fixed a trailing whitespace problem on an earlier PR I had submitted. I'm also not _100%_ certain that I'm correct in my analysis that the older regex was the wrong one for BSD grep (I'm certainly no expert on the differences), but the new one works on both my Linux machine and my Mac, regardless.
