### ISSUE TITLE
Can't build working firmware

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Arduino-Boards#12]
The last two versions ([e8a1c2a](https://github.com/keyboardio/Arduino-Boards/commit/e8a1c2a80951ee727ace42f076984f49c0408796) & [e7444b7](https://github.com/keyboardio/Arduino-Boards/commit/e7444b732e9fae35a0bd4c46752123ec9b25996c)) build non-functional firmware for me. I don't see any key input reaching the host. The previous version ([e3da471](https://github.com/keyboardio/Arduino-Boards/commit/e3da471dbd317b130427579e80a580be62d6b027)) is fine.

**Comment by gedankenexperimenter** [comment]
I've tried to narrow down the problem, but it's taking a while (interdependent modules) and I should have been asleep a couple of hours ago.

**Comment by obra** [comment]
this is the same issue simonclaudius reported against kaleidoscope. i’m betting it’s also the same issue that’s causing gergely to see hid report issues on linux.  it may be the horizontal scroll wheel code, which looks..not right... to me. 

i am also up past my bedtime else i would deal now

**Comment by gedankenexperimenter** [comment]
If it helps, I first saw what I think was this same problem yesterday morning. I thought it was my own fault (I was trying to build firmware with a new plugin), but when I backed up from a few master HEADs it started working again.

**Comment by algernon** [comment]
I'm almost sure it is the horizontal wheel stuff. I'll be spending most of my keyboard-time today on resolving the issue, one way or the other.

Worst case: we back horizontal wheel out. Hopefully it won't come to that.

**Comment by algernon** [comment]
keyboardio/KeyboardioHID#19 should address this, too, assuming you are on OSX. If you aren't, then this is a separate issue. In that case, I'll be very sad.

**Comment by gedankenexperimenter** [comment]
I will give that a try. Thanks!

**Comment by gedankenexperimenter** [comment]
This is fixed by keyboardio/KeyboardioHID#19. I think it makes sense to keep this open until that gets merged and a commit is made in here to include that change.
