### ISSUE TITLE
Please update submodules again

### ISSUE THREAD

**Issue by johnlindquist** [keyboardio/Arduino-Boards#7]
The `DualUse` has a major fix in master which is missing when you follow the "clone recursive" instructions on the main wiki page:

https://github.com/keyboardio/Kaleidoscope-DualUse/commit/de5c880cd1f7cf89be8630700ffd3317ae585fc8

**Comment by obra** [comment]
Done. (Note that this will _not_ update the version downloaded by the
Arduino Boards Manager. For that, I want to be a little more careful

**Comment by johnlindquist** [comment]
Thanks!
