### ISSUE TITLE
Strange build.core setting in arduino boards configuration

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/Arduino-Boards#9]
Shouldn't the following line 
https://github.com/keyboardio/Arduino-Boards/blob/ed7cd532b22247bf1827a681ec267dfbd99e5eaa/boards.txt#L35
and all similar lines read
```
model01.build.core=arduino
```
At least all similar lines in the file `/usr/local/arduino/hardware/arduino/avr/boards.txt` of a fresh Arduino installation read `*.build.core=arduino`.

This prevents automatic board recognition through other build systems.

**Comment by noseglasses** [comment]
Just that you understand, what I mean when I write about other build systems, see here: 
https://github.com/noseglasses/Kaleidoscope-CMake

Please note the Disclaimer ;-)

Unfortunately, my work to finish Kaleidoscope-CMake depends on this issue to be fixed or at least clarified.

**Comment by obra** [comment]
Until we fork the arduino core, I believe the current definition is correct:

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#referencing-another-core-variant-or-tool

**Comment by noseglasses** [comment]
Thank you for clarifying this and the helpful link provided.

**Comment by noseglasses** [comment]
This issue can be closed as it was a false positive. The answer led to a PR against another project I am relying on, where things go wrong with respect to referencing other cores. 
Thanks again.
